Repository FITPET-A/FITPET_BE, pull requests merged in 2024-08, with the labels that each got.

#66 [Refactor/#65] ADMIN API 도메인별로 폴더링 수정
  src/main/java/FITPET/dev/controller/AdminController.java
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/controller/InquiryController.java
  src/main/java/FITPET/dev/controller/InsuranceController.java
  src/main/java/FITPET/dev/controller/ProposalController.java
  src/main/java/FITPET/dev/service/AdminService.java
  src/main/java/FITPET/dev/service/ComparisonService.java
  src/main/java/FITPET/dev/service/InquiryService.java
  src/main/java/FITPET/dev/service/InsuranceService.java
  src/main/java/FITPET/dev/service/ProposalService.java
Labels: Refactor ♻️

#68 [Feat/#62] 유입 사이트 엔티티 설정
  src/main/java/FITPET/dev/entity/Comparison.java
  src/main/java/FITPET/dev/entity/RefSite.java
Labels: Feat 🩵

#70 [Ci/#64] CICD 구현
  Dockerfile
  src/main/java/FITPET/dev/controller/AdminController.java
  src/main/resources/application.yml
Labels: CI 🚀

#71 [Feat/#69] 유입 채널 생성, 조회, 삭제, 수정 API 구현
  src/main/java/FITPET/dev/common/status/ErrorStatus.java
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/ReferSiteController.java
  src/main/java/FITPET/dev/converter/ComparisonConverter.java
  src/main/java/FITPET/dev/converter/ReferSiteConverter.java
  src/main/java/FITPET/dev/dto/request/ComparisonRequest.java
  src/main/java/FITPET/dev/dto/request/ReferSiteRequest.java
  src/main/java/FITPET/dev/dto/response/ReferSiteResponse.java
  src/main/java/FITPET/dev/entity/Comparison.java
  src/main/java/FITPET/dev/entity/ReferSite.java
  src/main/java/FITPET/dev/repository/ReferSiteRepository.java
  src/main/java/FITPET/dev/service/ComparisonService.java
  src/main/java/FITPET/dev/service/ReferSiteService.java
Labels: Feat 🩵
