Repository FITPET-A/FITPET_BE, pull requests merged in 2024-09, with the labels that each got.

#75 [Chore/#74] 유입 채널 수정 request, 보헙 정보 API의 uri 수정
  src/main/java/FITPET/dev/controller/InsuranceController.java
  src/main/java/FITPET/dev/dto/request/ReferSiteRequest.java
Labels: Chore 🧹

#77 [Fix/#76] Webconfig 추가 및 cors 허용
  src/main/java/FITPET/dev/common/config/WebConfig.java
Labels: Fix 🛠️

#79 [Chore/#78] 상세품종명 검색 API 수정
  src/main/java/FITPET/dev/controller/AdminController.java
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/controller/InquiryController.java
  src/main/java/FITPET/dev/controller/InsuranceController.java
  src/main/java/FITPET/dev/controller/PetController.java
  src/main/java/FITPET/dev/controller/ProposalController.java
  src/main/java/FITPET/dev/controller/ReferSiteController.java
  src/main/java/FITPET/dev/dto/request/ProposalRequest.java
  src/main/java/FITPET/dev/repository/PetRepository.java
  src/main/java/FITPET/dev/service/PetService.java
  src/main/java/FITPET/dev/service/ReferSiteService.java
  src/main/resources/application.yml
Labels: Chore 🧹

#84 [Feat/#83] 제휴제안 상태 변경, 삭제, 상태 및 날짜에 따른 조회 기능 구현
  src/main/java/FITPET/dev/common/enums/ProposalStatus.java
  src/main/java/FITPET/dev/common/status/ErrorStatus.java
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/InquiryController.java
  src/main/java/FITPET/dev/controller/ProposalController.java
  src/main/java/FITPET/dev/converter/ProposalConverter.java
  src/main/java/FITPET/dev/dto/response/ProposalResponse.java
  src/main/java/FITPET/dev/entity/Proposal.java
  src/main/java/FITPET/dev/repository/ProposalRepository.java
  src/main/java/FITPET/dev/service/InquiryService.java
  src/main/java/FITPET/dev/service/ProposalService.java
Labels: Feat 🩵

#86 [Chore/#85] 견적 요청 생성 API Response 수정
  src/main/java/FITPET/dev/common/status/ErrorStatus.java
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/converter/ComparisonConverter.java
  src/main/java/FITPET/dev/service/ComparisonService.java
Labels: Fix 🛠️, Chore 🧹

#87 [Feat/#82] 관리자 마스터 계정 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/FITPET/dev/common/config/JwtAlgorithmConfiguration.java
  src/main/java/FITPET/dev/common/config/SecurityConfig.java
  src/main/java/FITPET/dev/common/security/dto/TokenDto.java
  src/main/java/FITPET/dev/common/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/FITPET/dev/common/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/FITPET/dev/common/security/jwt/JwtFilter.java
  src/main/java/FITPET/dev/common/security/jwt/JwtTokenProvider.java
  src/main/java/FITPET/dev/common/status/ErrorStatus.java
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/AdminController.java
  src/main/java/FITPET/dev/converter/AdminConverter.java
  src/main/java/FITPET/dev/converter/TokenConverter.java
  src/main/java/FITPET/dev/dto/request/AdminRequest.java
  src/main/java/FITPET/dev/dto/response/AdminResponse.java
  src/main/java/FITPET/dev/entity/Admin.java
  src/main/java/FITPET/dev/repository/AdminRepository.java
  src/main/java/FITPET/dev/service/AdminService.java
Labels: Feat 🩵

#88 [Feat/#72] : 견적서 삭제 API 구현
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/dto/request/ComparisonRequest.java
  src/main/java/FITPET/dev/entity/Comparison.java
  src/main/java/FITPET/dev/repository/ComparisonRepository.java
  src/main/java/FITPET/dev/service/ComparisonService.java
Labels: Feat 🩵

#90 [Feat/#80]: 유입채널 검색 API 구현
  src/main/java/FITPET/dev/common/status/SuccessStatus.java
  src/main/java/FITPET/dev/controller/ReferSiteController.java
  src/main/java/FITPET/dev/entity/Comparison.java
  src/main/java/FITPET/dev/entity/ReferSite.java
  src/main/java/FITPET/dev/repository/ComparisonRepository.java
  src/main/java/FITPET/dev/repository/ReferSiteRepository.java
  src/main/java/FITPET/dev/service/ComparisonService.java
  src/main/java/FITPET/dev/service/ReferSiteService.java
Labels: Feat 🩵

#91 [Chore/#89] : 1:1문의, 제휴제안, 견적서 삭제 수정
  src/main/java/FITPET/dev/common/config/SwaggerConfig.java
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/controller/InquiryController.java
  src/main/java/FITPET/dev/controller/ProposalController.java
  src/main/java/FITPET/dev/converter/InquiryConverter.java
  src/main/java/FITPET/dev/converter/ProposalConverter.java
  src/main/java/FITPET/dev/dto/request/ComparisonRequest.java
  src/main/java/FITPET/dev/dto/request/InquiryRequest.java
  src/main/java/FITPET/dev/dto/response/InquiryResponse.java
  src/main/java/FITPET/dev/dto/response/ProposalResponse.java
  src/main/java/FITPET/dev/entity/Inquiry.java
  src/main/java/FITPET/dev/repository/InquiryRepository.java
  src/main/java/FITPET/dev/repository/ProposalRepository.java
  src/main/java/FITPET/dev/service/ComparisonService.java
  src/main/java/FITPET/dev/service/InquiryService.java
  src/main/java/FITPET/dev/service/ProposalService.java
Labels: Chore 🧹

#94 [Fix/#93] PDF 다운로드 방식 변경
  src/main/java/FITPET/dev/common/utils/ApachePdfUtils.java
  src/main/java/FITPET/dev/converter/ComparisonConverter.java
  src/main/java/FITPET/dev/converter/InquiryConverter.java
  src/main/java/FITPET/dev/converter/InsuranceConverter.java
  src/main/java/FITPET/dev/converter/ProposalConverter.java
  src/main/java/FITPET/dev/converter/ReferSiteConverter.java
  src/main/java/FITPET/dev/dto/response/ComparisonResponse.java
  src/main/java/FITPET/dev/dto/response/InquiryResponse.java
  src/main/java/FITPET/dev/dto/response/InsuranceResponse.java
  src/main/java/FITPET/dev/dto/response/ProposalResponse.java
  src/main/java/FITPET/dev/dto/response/ReferSiteResponse.java
Labels: Fix 🛠️, Chore 🧹

#101 [Chore/#100] 견적서 요청 내역 조회 status all 조건 추가
  src/main/java/FITPET/dev/controller/ComparisonController.java
  src/main/java/FITPET/dev/service/ComparisonService.java
Labels: Chore 🧹
